import {defineType, defineField, defineArrayMember} from 'sanity'

/** Hero — SINGLETON for the landing cover. */
export const hero = defineType({
  name: 'hero',
  title: 'Homepage / Hero (shared)',
  type: 'document',
  fields: [
    defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
    defineField({name: 'headline', title: 'Headline', type: 'string'}),
    defineField({name: 'sub', title: 'Sub-copy', type: 'text', rows: 3}),
    defineField({name: 'videoId', title: 'Walkthrough video (YouTube ID)', type: 'string'}),
    defineField({name: 'background', title: 'Background image', type: 'image', options: {hotspot: true}, fields: [defineField({name: 'alt', type: 'string', title: 'Alt text'})]}),
    defineField({
      name: 'stats',
      title: 'Stat cards',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'value', title: 'Value', type: 'string'}),
            defineField({name: 'label', title: 'Label', type: 'string'}),
          ],
          preview: {select: {title: 'value', subtitle: 'label'}},
        }),
      ],
    }),
    /*
      Translations — one row per language, written by `npm run i18n:apply` into
      a DRAFT. Kept on the document rather than in a translated copy of it: the
      background image and the video id are the same in every language, and a
      duplicate would be one more thing to keep in step.

      Safe to edit by hand — correcting the wording here is the review step.
    */
    defineField({
      name: 'i18n',
      title: 'Translations',
      type: 'array',
      description: 'Generated by the translation scripts. Edit to correct the wording.',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'heroTranslation',
          fields: [
            defineField({name: 'locale', title: 'Language', type: 'string', readOnly: true}),
            defineField({name: 'sourceHash', title: 'Source fingerprint', type: 'string', readOnly: true}),
            defineField({name: 'sourceRev', title: 'Translated from revision', type: 'string', readOnly: true}),
            defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
            defineField({name: 'headline', title: 'Headline', type: 'string'}),
            defineField({name: 'sub', title: 'Sub-copy', type: 'text', rows: 3}),
            defineField({name: 'backgroundAlt', title: 'Background alt text', type: 'string'}),
            defineField({
              name: 'stats',
              title: 'Stat cards',
              type: 'array',
              of: [
                defineArrayMember({
                  type: 'object',
                  fields: [
                    defineField({name: 'value', title: 'Value', type: 'string'}),
                    defineField({name: 'label', title: 'Label', type: 'string'}),
                  ],
                }),
              ],
            }),
          ],
          preview: {select: {title: 'locale', subtitle: 'headline'}},
        }),
      ],
    }),
  ],
  preview: {prepare: () => ({title: 'Homepage / Hero'})},
})
