import {defineType, defineField, defineArrayMember} from 'sanity'

/**
 * Location — SINGLETON. All units share one building, so the address and the
 * "getting around" distances are edited here once, not per apartment.
 */
export const location = defineType({
  name: 'location',
  title: 'Location (shared)',
  type: 'document',
  fields: [
    defineField({name: 'heading', title: 'Eyebrow', type: 'string', initialValue: 'Getting around'}),
    defineField({name: 'addressLine', title: 'Address line', type: 'string'}),
    /*
      The map pin. Not translatable — a coordinate is the same fact in every
      language, like the WhatsApp number.

      A field rather than numbers in the code: the pin was hardcoded twice, in
      the map iframe and in the JSON-LD geo, and it sat about 1.7 km from the
      building for as long as both said so. Moving it used to mean a code change
      and a deploy.
    */
    defineField({
      name: 'lat',
      title: 'Map pin — latitude',
      type: 'number',
      description: 'Decimal degrees, e.g. 19.7683675. From Google Maps: right-click the building → the first number.',
      validation: (r) => r.min(-90).max(90),
    }),
    defineField({
      name: 'lng',
      title: 'Map pin — longitude',
      type: 'number',
      description: 'Decimal degrees, e.g. -70.5117769. The second number, negative in the Dominican Republic.',
      validation: (r) => r.min(-180).max(180),
    }),
    defineField({
      name: 'distances',
      title: 'Nearby places',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Place', type: 'string'}),
            defineField({name: 'value', title: 'Distance', type: 'string', description: 'e.g. "4 min walk"'}),
          ],
          preview: {select: {title: 'label', subtitle: 'value'}},
        }),
      ],
    }),
    /* Translations — see hero.ts for why these live on the document. */
    defineField({
      name: 'i18n',
      title: 'Translations',
      type: 'array',
      description: 'Generated by the translation scripts. Edit to correct the wording.',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'locationTranslation',
          fields: [
            defineField({name: 'locale', title: 'Language', type: 'string', readOnly: true}),
            defineField({name: 'sourceHash', title: 'Source fingerprint', type: 'string', readOnly: true}),
            defineField({name: 'sourceRev', title: 'Translated from revision', type: 'string', readOnly: true}),
            defineField({
              name: 'machine',
              title: 'Awaiting review',
              type: 'boolean',
              readOnly: true,
              description:
                'Written by the translation scripts and not yet read by a person. Saving the document in /admin clears it.',
            }),
            defineField({name: 'heading', title: 'Eyebrow', type: 'string'}),
            defineField({name: 'addressLine', title: 'Address line', type: 'string'}),
            defineField({
              name: 'distances',
              title: 'Nearby places',
              type: 'array',
              of: [
                defineArrayMember({
                  type: 'object',
                  fields: [
                    defineField({name: 'label', title: 'Place', type: 'string'}),
                    defineField({name: 'value', title: 'Distance', type: 'string'}),
                  ],
                }),
              ],
            }),
          ],
          preview: {select: {title: 'locale', subtitle: 'heading'}},
        }),
      ],
    }),
  ],
  preview: {prepare: () => ({title: 'Location', subtitle: 'Shared by all apartments'})},
})
