import {defineType, defineField, defineArrayMember} from 'sanity'

/**
 * Location — SINGLETON. All units share one building, so the address and the
 * "getting around" distances are edited here once, not per apartment.
 */
export const location = defineType({
  name: 'location',
  title: 'Location (shared)',
  type: 'document',
  fields: [
    defineField({name: 'heading', title: 'Eyebrow', type: 'string', initialValue: 'Getting around'}),
    defineField({name: 'addressLine', title: 'Address line', type: 'string'}),
    defineField({
      name: 'distances',
      title: 'Nearby places',
      type: 'array',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Place', type: 'string'}),
            defineField({name: 'value', title: 'Distance', type: 'string', description: 'e.g. "4 min walk"'}),
          ],
          preview: {select: {title: 'label', subtitle: 'value'}},
        }),
      ],
    }),
    /* Translations — see hero.ts for why these live on the document. */
    defineField({
      name: 'i18n',
      title: 'Translations',
      type: 'array',
      description: 'Generated by the translation scripts. Edit to correct the wording.',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'locationTranslation',
          fields: [
            defineField({name: 'locale', title: 'Language', type: 'string', readOnly: true}),
            defineField({name: 'sourceHash', title: 'Source fingerprint', type: 'string', readOnly: true}),
            defineField({name: 'sourceRev', title: 'Translated from revision', type: 'string', readOnly: true}),
            defineField({
              name: 'machine',
              title: 'Awaiting review',
              type: 'boolean',
              readOnly: true,
              description:
                'Written by the translation scripts and not yet read by a person. Saving the document in /admin clears it.',
            }),
            defineField({name: 'heading', title: 'Eyebrow', type: 'string'}),
            defineField({name: 'addressLine', title: 'Address line', type: 'string'}),
            defineField({
              name: 'distances',
              title: 'Nearby places',
              type: 'array',
              of: [
                defineArrayMember({
                  type: 'object',
                  fields: [
                    defineField({name: 'label', title: 'Place', type: 'string'}),
                    defineField({name: 'value', title: 'Distance', type: 'string'}),
                  ],
                }),
              ],
            }),
          ],
          preview: {select: {title: 'locale', subtitle: 'heading'}},
        }),
      ],
    }),
  ],
  preview: {prepare: () => ({title: 'Location', subtitle: 'Shared by all apartments'})},
})
